### ISSUE TITLE
Game Crashes When Taming SWEM Horse In Single Player

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWE-Alpha-Test#26]
Expected Behavior:
Taming horse without crashing game.

Current Behavior:
When trying to tame a horse it crashes game after one or two tries.

Possible Solution:
No clue.

Steps to Reproduce:
1: Open up an existing or new single player world
2: Spawn SWEM horse
3: Attempt to tame SWEM horse
4: Game crashes

SWEM Version: swem-1.16.5-0.21.1.3-Alpha
Does this happen in singleplayer? Yes
Does this happen in multiplayer? Idk

Detailed Description:
I tried opening a existing mc single player world to test something, spawned a SWEM horse and attempted to tame it and it crashed my game. I then tried making a new world to try this and the same thing happened.

Crash Report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 02/05/21 1:32 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:73) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233767_b_(SourceFile:81) ~[?:?] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.updateSelectedSpeed(SWEMHorseEntityBase.java:1636) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.func_110237_h(SWEMHorseEntityBase.java:522) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.func_230254_b_(SWEMHorseEntityBase.java:1400) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1049) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.1.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$444/1906549136.call(Unknown Source) [forge-1.16.5-36.0.1.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:73) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233767_b_(SourceFile:81) ~[?:?] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.updateSelectedSpeed(SWEMHorseEntityBase.java:1636) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.func_110237_h(SWEMHorseEntityBase.java:522) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at com.alaharranhonor.swem.entities.SWEMHorseEntityBase.func_230254_b_(SWEMHorseEntityBase.java:1400) ~[?:1.16.5-0.21.1.3-Alpha] {re:classloading}
	at net.minecraft.entity.MobEntity.func_184230_a(MobEntity.java:1049) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:940) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.client.multiplayer.PlayerController.func_187097_a(PlayerController.java:364) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Stardust312'/1, l='ClientLevel', x=171.55, y=4.00, z=-9.07]]
	Chunk stats: Client Chunk Cache: 3249, 1242
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,4,-16), Chunk: (at 0,0,0 in 11,-1; contains blocks 176,0,-16 to 191,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 353 game time, 353 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.1.jar:36.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$444/1906549136.call(Unknown Source) [forge-1.16.5-36.0.1.jar:36.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11021293376 bytes (10510 MB) / 13220446208 bytes (12608 MB) up to 16106127360 bytes (15360 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.1.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.1.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.1
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.1-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.1-universal.jar                 |Forge                         |forge                         |36.0.1              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Xaeros_Minimap_20.30.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.30.1             |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.11.jar                  |GeckoLib                      |geckolib3                     |3.0.11              |DONE      |NOSIGNATURE
		swem-1.16.5-0.21.1.3-Alpha.jar                    |Star Worm Equestrian Mod      |swem                          |1.16.5-0.21.1.3-Alph|DONE      |NOSIGNATURE
	Crash Report UUID: 60d8816c-2a8f-4028-b6a4-b5462c652f6b
	Launched Version: 1.16.5-forge-36.0.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by MagnusHJensen** [comment]
See #18 

This is a issue caused by the same thing.
